strings.txt
LMS-Community/slimserver pull request #1172
Opened 2024-10-02 15:28 UTC by LDulac

Portuguese translation update

2024-10-02 15:30 UTC, LDulac reviewed
Update to the Portuguese transalation

2024-10-05 12:36 UTC, mavit requested changes

2024-10-05 12:36 UTC, mavit commented on strings.txt
> +	EN	Wnot supported
Looks like a typo, here.

2024-10-13 06:30 UTC, michaelherger commented
Thanks @LDulac! 

Please double check your changes. As @mavit has pointed out there have been some accidental changes to other languages. And there are lines where you added a space to the end of the line, but didn't change anything at all. Make sure there's no such "noise" in the PR, but really only wanted changes. Thanks again!

2024-10-14 14:07 UTC, LDulac commented
Hi Michael,
I do not recall having touched another language version but if I did, my apologies and please tell me what can I do to remedy it.
As to the added space at the end of a line I checked it in Notepad ++. I looked for instances of “ \r\n” (which is the same as “Space New Line” without commas) but the program did not find a single match.
I will have a deeper look to see where I may have done something wrong. Please bear with me.
Rgds
Luis


From: Michael Herger ***@***.***>
Sent: 13 October 2024 07:31
To: LMS-Community/slimserver ***@***.***>
Cc: LDulac ***@***.***>; Mention ***@***.***>
Subject: Re: [LMS-Community/slimserver] strings.txt (PR #1172)


Thanks @LDulac<https://github.com/LDulac>!

Please double check your changes. As @mavit<https://github.com/mavit> has pointed out there have been some accidental changes to other languages. And there are lines where you added a space to the end of the line, but didn't change anything at all. Make sure there's no such "noise" in the PR, but really only wanted changes. Thanks again!

—
Reply to this email directly, view it on GitHub<https://github.com/LMS-Community/slimserver/pull/1172#issuecomment-2408844999>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AWRXHBWOVLC4NFL5VHQR7RDZ3IHQXAVCNFSM6AAAAABPH5VSJSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMBYHA2DIOJZHE>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2024-10-14 14:13 UTC, michaelherger commented on strings.txt
> +	PT	Esta opção permite que escolha se o alarme se repita mais que uma vez. Se a opção for "Não" o alarme desligar-se-á depois de tocar. Não tornará a tocar até que o torne a ligar.
You can look at the changes on GitHub and you'll see the changed lines. 

If your editor can handle regexes, then you could probably search for `\s+$` and remove those. But please only do so for the lines you modified!

2024-10-14 14:14 UTC, michaelherger commented on strings.txt
> +	FR	Voici les formats disponibles. Ils peuvent être choisis dans l'interface Web et les platines. Pour supprimer un format, effacez le contenu de la zone de texte. Placez votre curseur dans la zone d
A French line changed?

There's a free Git client called Sourcetree which would give you a nice GUI to revert such unwanted changes.

2024-10-14 20:22 UTC, michaelherger commented
Ok, your last commit was exactly how you should fix those issues. Now please go through all the changes to make sure no unwanted modification or whitespace or whatever is left. Browsing https://github.com/LMS-Community/slimserver/pull/1172/files you'll find modifications in darker colors. Pay particular attention to non PT changes. Thanks!

2024-11-27 15:46 UTC, michaelherger commented
@LDulac - did you plan to finalise this any time soon? I would like to release LMS9 really soon.

2024-11-27 17:54 UTC, LDulac commented
> @LDulac - did you plan to finalise this any time soon? I would like to release LMS9 really soon.

Michael, I am sorry but wasn't aware that you were counting on my translation for the LMS9 release. Please give me 1 week from tomorrow to try and improve it. Please let me know if that is acceptable.

2024-11-28 05:30 UTC, michaelherger commented
No worries! Take your time. I only wanted to know whether you were ready. This can be merged any time. It just won't make the LMS 9.0.0 release, as I really need to get it out this week(end).

2026-06-11 04:37 UTC, michaelherger commented
Ping?

2026-08-17 22:32 UTC, closed without merging