Fix Gapless playback for SB1
LMS-Community/slimserver pull request #369
Opened 2020-06-15 07:07 UTC by michaldie

Fix to address this issue : 

https://github.com/Logitech/slimserver/issues/366

the code does work as described in the issue - 
however it is not very pretty - but then I am no Perl programmer ..
comments welcome

Michael

2020-06-15 15:56 UTC, michaelherger requested changes
Please apply the minor changes commented inline. The patch itself overall makes sense. Thanks!

2020-06-15 15:56 UTC, michaelherger commented on Slim/Player/Squeezebox1.pm
> +                        if ( $playingSong ) {
Could you please revert whitespace changes? Make sure you're using tabs rather than spaces.

2020-06-15 15:56 UTC, michaelherger commented on Slim/Player/Squeezebox1.pm
> +                        if ( $playingSong ) {
You should probably get the two `currentTrack` objects beforehand and check their existence, too.

```perl
my $playingTrack = $playingSong->currentTrack;
my $songTrack = $song->currentTrack;

if ($playingTrack && $songTrack && $playingTrack->channels == $songTrack->channels && ...
```

2020-06-15 15:56 UTC, michaelherger commented on Slim/Player/Squeezebox1.pm
> +        main::DEBUGLOG && logger('player.playlist')->debug("Restart decoder required");
I'd say the `player` logging object would be correct here.

2020-06-17 20:21 UTC, michaldie commented
Ok, new commit is in place.

2020-06-18 06:47 UTC, mherger approved these changes

2020-06-18 06:47 UTC, merged

2020-06-18 06:48 UTC, mherger commented
Thanks!